### ISSUE TITLE
move to `package-lock.json` only and use `npm ci`

### ISSUE THREAD

**Issue by fncolon** [fncolon/encryptlab#32]
## Description

This repository will standardize to use npm.

## Tasks

- [x] Remove `package-lock.json` under the `.gitignore` file
- [x] use `npm ci` instead of `npm install` on CI workflow (npm ci only uses the version in the lockfile and produces an error if the package-lock.json and package.json are out of sync.)
- [x] Add `package-lock.json`
